### ISSUE TITLE
per-language git URL parsing

### ISSUE THREAD

**Issue by tushar-deepsource** [deepsourcelabs/depend#88]
Currently we don't parse the git url specifications for each package format.

`requirements.txt` for example uses this: `git+https://github.com/foobar/foobar@branch`

Poetry uses a dictionary. etc.

**Comment by NobleMathews** [comment]
Python

requirements.txt
```
git+https://github.com/user/repo.git@branch_or_tag_or_commit_hash
```

setup.py
```python
from setuptools import setup, find_packages

setup(
    name="example",
    version="0.1.0",
    description="Example package",
    packages=find_packages(),
    install_requires=[
        "requests @ git+https://github.com/user/repo.git@branch-or-tag-or-commit-hash"
    ],
    author="Your Name"
)

```

setup.cfg
```cfg
[options]
install_requires =
    requests @ git+https://github.com/user/repo.git@branch-or-tag-or-commit-hash

[metadata]
name = example
version = 0.1.0
description = Example package
author = Your Name

```

poetry.toml
```toml
[tool.poetry.dependencies]
python = "^3.9"
requests = {git = "https://github.com/user/repo.git", tag = "v0.1.0"}

[tool.poetry.dev-dependencies]
pytest = "^6.2"
```

pyproject.toml (not sure? `dependencies =` and `package.build`)
```toml
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.install_requires]
requests = {git = "https://github.com/requests/requests.git", tag = "v2.26.0"}

```

pipfile
```
[packages]
requests = {git = "https://github.com/user/repo.git", ref = "branch-or-tag-or-commit-hash"}

[dev-packages]
pytest = "*"
```

**Comment by NobleMathews** [comment]
Go

```mod
module github.com/user/repo

require (
    github.com/user/repo v0.1.0
    github.com/otheruser/otherrepo v1.2.0
)

replace github.com/user/repo => github.com/user/repo v0.1.0-0.20220101010101-hash

```

**Comment by NobleMathews** [comment]
Rust Cargo.toml

```toml
[dependencies]
repo = { git = "https://github.com/user/repo.git", tag = "v0.1.0" }
```
